image: bagofwords/bagofwords:latest
host: app.bagofwords.com
registry:
  name: bow-app-registry
  url: docker.io
postgresql:
  auth:
    username: ""
    password: ""
    database: ""
    existingSecret: ""
  primary:
    persistence:
      size: 20Gi
ingress:
  enabled: true
  className: nginx
  tls: true
  clusterIssuerName: prod-cluster-issuer
serviceAccount:
  name: bowapp
  imagePullSecret: bowapp-pull-secret
  annotations: {}
config:
  secretRef: ""
  googleOauthEnabled: false
  googleClientId: ""
  googleClientSecret: ""
  defaultLLMApiKey: ""
  smtpPassword: ""
  encryptionKey: ""
