image: bagofwords/bagofwords:latest
host: app.bagofwords.com
registry:
  name: bow-app-registry
  url: docker.io
postgresql:
  auth:
    username: ""
    password: ""
    database: ""
  primary:
    persistence:
      size: 20Gi
    readinessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 6
config:
  googleClientId: ""
  googleClientSecret: ""
  defaultLLMApiKey: ""
  smtpPassword: ""
  encryptionKey: ""