name: End-to-End Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run E2E tests
      id: tests
      working-directory: ./backend
      env:
        TESTING: "true"
      run: |
      pytest -m e2e --disable-warnings
      continue-on-error: true

    - name: Trigger Docker build workflow
      if: steps.tests.outcome == 'success' && github.ref == 'refs/heads/main'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: e2e-tests-passed